[book]
authors = ["zhengxiaoyao0716"]
language = "zh"
multilingual = false
src = "src"
title = "Tensai Suraimu do Baka Meido"

[output.html]
git-repository-url = "https://github.com/tensai-suraimu/tensai-suraimu.github.io"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/tensai-suraimu/tensai-suraimu.github.io/edit/master/guide/{path}"
